# Generated by Django 5.0.6 on 2024-07-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('COM', 'Comida'), ('LIB', 'Librería'), ('SNA', 'Snacks'), ('BEB', 'Bebidas'), ('IMP', 'Impresiones'), ('ELE', 'Electrónicos'), ('ASE', 'Aseo'), ('OTR', 'Otros')], default='OTR', max_length=3),
        ),
    ]
