# Generated by Django 5.0.6 on 2024-07-22 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_venta_confirmado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tienda',
            old_name='dueño',
            new_name='dueno',
        ),
    ]
