# Generated by Django 5.0.6 on 2024-07-19 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activesessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesessions',
            name='expire_date',
        ),
    ]
